apiVersion: apps/v1
kind: Deployment
metadata:
  name: avinash-capstone-deployment
  namespace: avinash-capstone-ns
  labels:
    app: avinash-capstone-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: avinash-capstone-app
  template:
    metadata:
      labels:
        app: avinash-capstone-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - name: avinash-capstone-app
        image: 779081108163.dkr.ecr.us-east-2.amazonaws.com/avinash-capstone:latest
        ports:
        - name: http
          containerPort: 9090
        imagePullPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux

