---
- name: Copy deployment configuration
  copy:
    src: "create_deployment_k8.yaml"
    dest: /tmp

- name: Apply deployment configuration
  shell: "kubectl apply -f create_deployment_k8.yaml"
  args:
    chdir: /tmp