apiVersion: v1
kind: Service
metadata:
  name: avi-capstone-service
  namespace: avinash-capstone-ns
  labels:
    app: avinash-capstone-app
spec:
  type: LoadBalancer
  selector:
    app: avinash-capstone-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
